sudo: false
language: node_js
node_js:
  - '6.0'
cache:
  directories:
    - node_modules
branches:
  only:
    - next
notifications:
  email: false
before_script:
  - yarn prune
script:
  - yarn run docs
after_success:
  - bash ./scripts/deploy-docs.sh
env:
  global:
    - GH_USER: juicycleff
    - GH_REPO: ultimate-backend
