version: "3.2"

services:
  services-account:
    build:
      context: ""
      dockerfile: apps/service-account/Dockerfile
    image: "${DOCKER_REGISTRY}/${DOCKER_REPO:?err}/service-account:${IMAGE_TAG:?err}"
    restart: always
    ports:
      - 50054:50054
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  services-access:
    build:
      context: ""
      dockerfile: apps/service-access/Dockerfile
    image: "${DOCKER_REGISTRY}/${DOCKER_REPO:?err}/service-access:${IMAGE_TAG:?err}"
    restart: always
    ports:
    - 50089:50089
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  services-billing:
    build:
      context: ""
      dockerfile: apps/service-billing/Dockerfile
    image: "${DOCKER_REGISTRY}/${DOCKER_REPO:?err}/service-billing:${IMAGE_TAG:?err}"
    restart: always
    ports:
    - 50067:50067
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  services-notification:
    build:
      context: ""
      dockerfile: apps/service-notification/Dockerfile
    image: "${DOCKER_REGISTRY}/${DOCKER_REPO:?err}/service-notification:${IMAGE_TAG:?err}"
    restart: always
    ports:
    - 50044:50044
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  services-role:
    build:
      context: ""
      dockerfile: apps/service-role/Dockerfile
    image: "${DOCKER_REGISTRY}/${DOCKER_REPO:?err}/service-role:${IMAGE_TAG:?err}"
    restart: always
    ports:
    - 50052:50052
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  services-tenant:
    build:
      context: ""
      dockerfile: apps/service-tenant/Dockerfile
    image: "${DOCKER_REGISTRY}/${DOCKER_REPO:?err}/service-tenant:${IMAGE_TAG:?err}"
    restart: always
    ports:
    - 50053:50053
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  api-admin:
    build:
      context: ""
      dockerfile: apps/api-admin/Dockerfile
    image: "${DOCKER_REGISTRY}/${DOCKER_REPO:?err}/api-admin:${IMAGE_TAG:?err}"
    restart: always
    ports:
    - 50020:50020
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  eventstore:
    container_name: eventstore-node
    ports:
      - '2113:2113'
      - '1113:1113'
    image: eventstore/eventstore:release-5.0.8
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
      kompose.image-pull-policy: "Always"
