version: "3.2"

services:
  service-account:
    build:
      context: .
      dockerfile: apps/service-account/Dockerfile
      args:
        NODE_ENV: development
    image: "service-account:latest"
    restart: always
    ports:
      - 50054:50054
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  service-access:
    build:
      context: .
      dockerfile: apps/service-access/Dockerfile
      args:
        NODE_ENV: development
    image: "service-access:latest"
    restart: always
    ports:
      - 50089:50089
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  service-billing:
    build:
      context: .
      dockerfile: apps/service-billing/Dockerfile
      args:
        NODE_ENV: development
    image: "service-billing:latest"
    restart: always
    ports:
      - 50067:50067
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  service-notification:
    build:
      context: .
      dockerfile: apps/service-notification/Dockerfile
      args:
        NODE_ENV: development
    image: "service-notification:latest"
    restart: always
    ports:
      - 50044:50044
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  service-role:
    build:
      context: .
      dockerfile: apps/service-role/Dockerfile
      args:
        NODE_ENV: development
    image: "service-role:latest"
    restart: always
    ports:
      - 50052:50052
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  service-tenant:
    build:
      context: .
      dockerfile: apps/service-tenant/Dockerfile
      args:
        NODE_ENV: development
    image: "service-tenant:latest"
    restart: always
    ports:
      - 50053:50053
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  api-admin:
    build:
      context: .
      dockerfile: apps/api-admin/Dockerfile
      args:
        NODE_ENV: development
    image: "api-admin:latest"
    restart: always
    ports:
      - 50020:50020
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"
      kompose.image-pull-secret: "gitlabregcrednew"
      kompose.image-pull-policy: "Always"

  eventstore:
    container_name: eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    image: eventstore/eventstore
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
      kompose.image-pull-policy: "Always"

  memcached:
    container_name: memcached
    image: launcher.gcr.io/google/memcached1
    ports:
      - "11211:11211"

  redis:
    container_name: redis
    image: redis
    expose:
      - 6379
