version: '3.2'

services:

  services-auth:
    build:
      context: .
      dockerfile: docker/prod/service-auth.Dockerfile
    image: ultimatebackend/service-auth
    restart: always
    ports:
      - 9900:9900
    environment:
      - PORT=9900
    labels:
      kompose.service.type: clusterip

  services-project:
    build:
      context: .
      dockerfile: docker/prod/service-project.Dockerfile
    image: ultimatebackend/service-project
    restart: always
    ports:
      - 9100:9100
    environment:
      - PORT=9100
    labels:
      kompose.service.type: clusterip

  services-user:
    build:
      context: .
      dockerfile: docker/prod/service-user.Dockerfile
    image: ultimatebackend/service-user
    restart: always
    ports:
      - 9000:9000
    environment:
      - PORT=9000
    labels:
      kompose.service.type: clusterip

  services-notification:
    build:
      context: .
      dockerfile: docker/prod/service-notification.Dockerfile
    image: ultimatebackend/service-notification
    restart: always
    ports:
      - 9400:9400
    environment:
      - PORT=9400
    labels:
      kompose.service.type: clusterip

  services-tenant:
    build:
      context: .
      dockerfile: docker/prod/service-tenant.Dockerfile
    image: ultimatebackend/service-tenant
    restart: always
    ports:
      - 9200:9200
    environment:
      - PORT=9200
    labels:
      kompose.service.type: clusterip

  services-payment:
    build:
      context: .
      dockerfile: docker/prod/service-payment.Dockerfile
    image: ultimatebackend/service-payment
    restart: always
    ports:
      - 9300:9300
    environment:
      - PORT=9300
    labels:
      kompose.service.type: clusterip

  gateway-admin:
    build:
      context: .
      dockerfile: docker/prod/gateway-admin.Dockerfile
    image: ultimatebackend/gateway-admin
    restart: always
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - PROJECT_ENDPOINT=http://services-project:9100/graphql
      - PROJECT_PATH=project
      - AUTH_ENDPOINT=http://services-auth:9900/graphql
      - AUTH_PATH=auth
      - USER_ENDPOINT=http://services-auth:9000/graphql
      - USER_PATH=user

    depends_on:
      - services-auth
      - services-project
      - services-user
    links:
      - services-auth
      - services-project
      - services-user
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"

  gateway-client:
    build:
      context: .
      dockerfile: docker/prod/gateway-client.Dockerfile
    image: ultimatebackend/gateway-client
    restart: always
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - PROJECT_ENDPOINT=http://services-project:9100/graphql
      - PROJECT_PATH=project
      - AUTH_ENDPOINT=http://services-auth:9900/graphql
      - AUTH_PATH=auth
      - USER_ENDPOINT=http://services-auth:9000/graphql
      - USER_PATH=user

    depends_on:
      - services-project
    links:
      - services-project
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"

  eventstore:
    container_name: eventstore-node
    ports:
      - '2113:2113'
      - '1113:1113'
    image: eventstore/eventstore
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"
