apiVersion: v1
kind: ServiceAccount
metadata:
  name:  azure-deploy
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-deploy-secret
  annotations:
    kubernetes.io/service-account.name: azure-deploy
type: kubernetes.io/service-account-token
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  azure-deploy-role
  namespace: development
rules: # ## Customize these to meet your requirements ##
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "deployments/rollback", "deployments/scale", "replicasets", "replicasets/scale", "statefulsets", "statefulsets/scale"]
    verbs: ["create", "delete", "get", "update", "patch", "list", "deletecollection"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "daemonsets", "deployments/rollback", "deployments/scale", "replicasets", "replicasets/scale", "replicationcontrollers/scale"]
    verbs: ["create", "delete", "get", "update", "patch", "list", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "update", "patch", "list", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods/attach", "pods/exec", "pods/portforward", "pods/proxy", "secrets", "services/proxy"]
    verbs: ["list", "get", "switch"]
  - apiGroups: [""]
    resources: ["horizontalpodautoscalers"]
    verbs: ["watch", "get", "list"]
  - apiGroups: ["autoscaling"]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["create", "delete", "get", "update", "patch", "deletecollection"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["create", "delete", "get", "update", "patch", "list"]
  - apiGroups: [""]
    resources: ["configmaps", "endpoints", "persistentvolumeclaims", "pods", "replicationcontrollers", "replicationcontrollers/scale", "serviceaccounts", "services"]
    verbs: ["create", "delete", "get", "update", "patch", "deletecollection", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "endpoints", "persistentvolumeclaims", "pods", "replicationcontrollers", "replicationcontrollers/scale", "serviceaccounts", "services"]
    verbs: ["create", "delete", "get", "update", "patch", "deletecollection", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-rolebinding
subjects:
  - kind: ServiceAccount
    name:  azure-deploy
    namespace: default
roleRef:
  kind: ClusterRole
  name: azure-deploy-role
  apiGroup: rbac.authorization.k8s.io

