# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.12

    working_directory: ~/ultimate-backend

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: install-snyk
          command: 'sudo npm install -g snyk'

      - run: # run snyk help - test snyk is installed and working
          name: snyk-help
          command: snyk --help
      - run: # run snyk auth - authenticate snyk use environment variables to add token
          name: snyk auth
          command: snyk auth $SNYK_TOKEN

      # run tests!
      - run: yarn test

      # run cov tests!
      - run: yarn test:cov

      # run e2e tests!
      - run: yarn test:e2e
