dns: localhost
name: "Ultimate Backend"

app:
  url: http://${dns}
  cache: redis

mongodb:
  defaultUri: 'mongodb://localhost/'

payment:
  stripe:
    secretKey: "sk_test_HT0RcNMg3LxROE7v099gcwIs00WUH3Ljm9"
    publishKey: "pk_test_VXYW9SvpksV2DC2bVVZYKM2w"

eventstore:
  poolMax:
  poolMin:
  streamProtocol: "http"
  hostname: "localhost"
  httpPort: 2113
  httpPotocol: "http"
  tcpPassword: "changeit"
  tcpUsername: "admin"
  tctPort: 1113
  tcpProtocol: tcp

redis:
  host: "localhost"
  port: "6379"

sendgrid:
  api: "SENDGRID-API-KEY"
  sender: dummy@dumm.com

casbin:
  dbUri: ${mongodb.defaultUri}
  dbName: "service-auth"

services:
  auth:
    port: 9900
    grpcPort: 7900
    mongodb:
      uri: ${mongodb.defaultUri}
      name: "service-auth"
      options:

  tenant:
    port: 9200
    grpcPort: 7200
    mongodb:
      uri: ${mongodb.defaultUri}
      name: "service-tenant"
      options:

  user:
    port: 9000
    grpcPort: 7000
    mongodb:
      uri: ${mongodb.defaultUri}
      name: "service-user"
      options:

  project:
    port: 9100
    grpcPort: 7100
    mongodb:
      uri: ${mongodb.defaultUri}
      name: "service-project"
      options:

  notification:
    port: 9400
    grpcPort: 7400
    mongodb:
      uri: ${mongodb.defaultUri}
      name: "service-notification"
      options:
    sendgrid:
      api: "SENDGRID-API-KEY"
      senderEmail:

  billing:
    port: 9300
    grpcPort: 7300
    mongodb:
      uri: ${mongodb.defaultUri}
      name: "service-payment"
      options:

  plan:
    port: 9500
    grpcPort: 7500
    mongodb:
      uri: ${mongodb.defaultUri}
      name: "service-payment"
      options:


gateway:
  admin:
    port: 4000
  client:
    port: 5000
